import type { Coordinates,RouteLeg } from "../types";

export type RouteCandidate={id:string;name:string;coordinates:Coordinates};
export type QualifiedRoute<T extends RouteCandidate>={candidate:T;route:RouteLeg;routeSource:"live"|"estimated";routeError?:unknown};
const toRad=(value:number)=>value*Math.PI/180;
export const coordinateMiles=(a:Coordinates,b:Coordinates)=>{const dLat=toRad(b.latitude-a.latitude),dLon=toRad(b.longitude-a.longitude),value=Math.sin(dLat/2)**2+Math.cos(toRad(a.latitude))*Math.cos(toRad(b.latitude))*Math.sin(dLon/2)**2;return 3958.8*2*Math.atan2(Math.sqrt(value),Math.sqrt(1-value))};
export function estimatedRoute(from:string,candidate:RouteCandidate,origin:Coordinates):RouteLeg{const distanceMiles=Math.ceil(coordinateMiles(origin,candidate.coordinates)*1.3),driveMinutes=Math.ceil(distanceMiles/42*60);return{from,to:candidate.name,distanceMiles,driveMinutes,source:"estimate"}}
export async function mapWithConcurrency<T,R>(items:T[],limit:number,mapper:(item:T,index:number)=>Promise<R>):Promise<R[]>{const results=new Array<R>(items.length),workers=Array.from({length:Math.min(Math.max(1,limit),items.length)},async(_,worker)=>{for(let index=worker;index<items.length;index+=Math.min(Math.max(1,limit),items.length))results[index]=await mapper(items[index],index)});await Promise.all(workers);return results}
export async function qualifyRoutes<T extends RouteCandidate>(candidates:T[],from:string,origin:Coordinates,maxDriveMinutes:number,route:(candidate:T)=>Promise<RouteLeg>,concurrency=2):Promise<Array<QualifiedRoute<T>>>{const routed=await mapWithConcurrency(candidates,concurrency,async candidate=>{try{const live=await route(candidate);return{candidate,route:live,routeSource:"live" as const}}catch(routeError){return{candidate,route:estimatedRoute(from,candidate,origin),routeSource:"estimated" as const,routeError}}});return routed.filter(result=>result.route.driveMinutes<=maxDriveMinutes)}
export function mergeProviderCandidates<T extends RouteCandidate>(nps:T[],ridb:T[]):T[]{const seen=new Set<string>();return[...nps,...ridb].filter(candidate=>{const key=`${candidate.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${candidate.coordinates.latitude.toFixed(2)}-${candidate.coordinates.longitude.toFixed(2)}`;if(seen.has(key))return false;seen.add(key);return true})}
