import type { CampingPreference, DiscoverFilters, Interest, RigProfile, RoadStop, Trip } from "./types";
export const interests:Interest[]=["Scenic","Small towns","Hiking","Lake","Fishing","Events","Food","Museums","Amusement parks","Relaxing"];
export const campingPreferences:CampingPreference[]=["Full hookups","Electric","State park","Boondocking","Pull-through","Dog friendly"];
export const seededRig:RigProfile={home:"Pendleton, Kentucky 40055",rv:{year:2022,manufacturer:"Starcraft",model:"Autumn Ridge 26BHS",type:"Travel trailer",lengthFt:30.75,heightFt:11.08,widthFt:8,gvwr:7500,service:"30 amp",slides:1,freshTank:42,generator:false},towVehicle:{year:2025,manufacturer:"Chevrolet",model:"Silverado 2500HD",engine:"6.6L gasoline V8",fuel:"Gasoline",tankGallons:36,towingMpg:9}};
export const defaultFilters:DiscoverFilters={start:seededRig.home,leave:"2026-09-18",returnDate:"2026-09-20",maxDriveHours:4,adults:2,kids:2,dogs:1,interests:["Scenic","Hiking","Small towns"],preferences:["Electric","State park","Dog friendly"]};
export const trips:Trip[]=[
 {id:"red-river-gorge",destination:"Red River Gorge",region:"Slade, Kentucky",coordinates:{latitude:37.8333,longitude:-83.6167},driveMinutes:142,distanceMiles:140,weather:"72° / 54° · Planning estimate",campgrounds:7,activities:18,tags:["Scenic","Hiking","Small towns"],preferences:["Electric","State park","Dog friendly"],fuelCost:93,campgroundCost:72,otherCost:20,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Red%20River%20Gorge%2C%20Daniel%20Boone%20National%20Forest%2C%20Kentucky%20LOC%202002626210.jpg?width=1600",imageCredit:{label:"Library of Congress via Wikimedia Commons",sourceUrl:"https://commons.wikimedia.org/wiki/File:Red_River_Gorge,_Daniel_Boone_National_Forest,_Kentucky_LOC_2002626210.jpg",license:"Public domain"},explanation:"Strong scenery, a manageable weekend drive, and enough nearby activities without spending half the weekend towing.",routeNote:"Mostly interstate with a short two-lane approach. No known seeded restriction conflicts.",novelty:82,weatherScore:92,priceScore:91,rigFit:98,activityScore:96,campgroundNames:["Middle Fork Campground","Whittleton Campground","Natural Bridge Campground"],events:["Mountain arts market","Guided natural bridge hike"]},
 {id:"brown-county",destination:"Brown County",region:"Nashville, Indiana",coordinates:{latitude:39.1562,longitude:-86.2167},driveMinutes:128,distanceMiles:112,weather:"70° / 51° · Planning estimate",campgrounds:5,activities:14,tags:["Small towns","Food","Hiking"],preferences:["Electric","State park","Dog friendly"],fuelCost:75,campgroundCost:84,otherCost:35,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Parque%20Estatal%20Brown%20County%2C%20Indiana%2C%20Estados%20Unidos%2C%202012-10-14%2C%20DD%2001.jpg?width=1600",imageCredit:{label:"Diego Delso via Wikimedia Commons",sourceUrl:"https://commons.wikimedia.org/wiki/File:Parque_Estatal_Brown_County,_Indiana,_Estados_Unidos,_2012-10-14,_DD_01.jpg",license:"CC BY-SA 3.0"},explanation:"A compact arts town, shaded trails, and an easy tow make this a low-friction weekend with plenty to explore.",routeNote:"Interstate-heavy route; campground approach should be verified with live routing.",novelty:76,weatherScore:89,priceScore:86,rigFit:94,activityScore:89,campgroundNames:["Brown County State Park","Bill Monroe Music Park"],events:["Village art walk","Local food festival"]},
 {id:"mammoth-cave",destination:"Mammoth Cave",region:"Cave City, Kentucky",coordinates:{latitude:37.1870,longitude:-86.1005},driveMinutes:132,distanceMiles:121,weather:"74° / 56° · Planning estimate",campgrounds:8,activities:12,tags:["Hiking","Museums","Relaxing"],preferences:["Electric","State park","Pull-through"],fuelCost:81,campgroundCost:68,otherCost:38,image:"https://www.nps.gov/common/uploads/structured_data/3C7A098E-1DD8-B71B-0B3FE2E0AA8115DA.jpg",imageCredit:{label:"National Park Service",sourceUrl:"https://www.nps.gov/maca/learn/photosmultimedia/photogallery.htm",license:"NPS public domain"},explanation:"A reliable rig-fit base with one standout anchor activity and a relaxed pace around the park.",routeNote:"Straightforward approach in seed data. Live height, weight, and closure checks are not yet connected.",novelty:70,weatherScore:91,priceScore:90,rigFit:97,activityScore:86,campgroundNames:["Mammoth Cave Campground","Cave Country RV Campground"],events:["Evening ranger program"]},
 {id:"hocking-hills",destination:"Hocking Hills",region:"Logan, Ohio",coordinates:{latitude:39.4306,longitude:-82.5390},driveMinutes:205,distanceMiles:191,weather:"68° / 49° · Planning estimate",campgrounds:6,activities:16,tags:["Scenic","Hiking","Relaxing"],preferences:["Electric","State park","Dog friendly"],fuelCost:127,campgroundCost:92,otherCost:25,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Ash%20Cave%20-%20Hocking%20Hills%20State%20Park.jpg?width=1600",imageCredit:{label:"Wikimedia Commons contributor",sourceUrl:"https://commons.wikimedia.org/wiki/File:Ash_Cave_-_Hocking_Hills_State_Park.jpg",license:"Creative Commons; see source"},explanation:"The longest tow in this set earns its place with exceptional trail density and a quiet, scenic reset.",routeNote:"Within four hours in seed data. Final local-road suitability needs a live RV-aware route provider.",novelty:94,weatherScore:84,priceScore:78,rigFit:90,activityScore:94,campgroundNames:["Hocking Hills State Park","Top O’ the Caves"],events:["Naturalist night hike"]},
 {id:"land-between-lakes",destination:"Land Between the Lakes",region:"Golden Pond, Kentucky",coordinates:{latitude:36.7855,longitude:-88.0720},driveMinutes:224,distanceMiles:220,weather:"76° / 58° · Planning estimate",campgrounds:9,activities:20,tags:["Lake","Fishing","Scenic"],preferences:["Electric","Boondocking","Dog friendly"],fuelCost:146,campgroundCost:64,otherCost:30,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Landbetweenlakes%20oli%202016281%20lrg.jpg?width=1600",imageCredit:{label:"NASA Earth Observatory via Wikimedia Commons",sourceUrl:"https://commons.wikimedia.org/wiki/File:Landbetweenlakes_oli_2016281_lrg.jpg",license:"Public domain"},explanation:"Worth the longer pull for waterfront options, fishing, and room to spread out once you arrive.",routeNote:"Longer highway drive. Seeded options include sites reported to accommodate 31-foot trailers.",novelty:88,weatherScore:88,priceScore:84,rigFit:93,activityScore:95,campgroundNames:["Hillman Ferry Campground","Energy Lake Campground"],events:["Wildlife refuge program"]},
 {id:"new-river-gorge",destination:"New River Gorge",region:"Fayetteville, West Virginia",coordinates:{latitude:38.0708,longitude:-81.0750},driveMinutes:245,distanceMiles:232,weather:"69° / 50° · Planning estimate",campgrounds:4,activities:17,tags:["Scenic","Hiking","Food"],preferences:["Electric","Dog friendly"],fuelCost:154,campgroundCost:96,otherCost:40,image:"https://www.nps.gov/common/uploads/structured_data/3C7E74C5-1DD8-B71B-0B1C6AE92E6FC4C0.jpg",imageCredit:{label:"National Park Service",sourceUrl:"https://www.nps.gov/neri/learn/photosmultimedia/index.htm",license:"NPS public domain"},explanation:"A bigger weekend with dramatic scenery and a lively trail-town base, best when your drive window has some flexibility.",routeNote:"Slightly beyond the default four-hour limit and omitted unless tolerance is increased.",novelty:96,weatherScore:86,priceScore:71,rigFit:86,activityScore:96,campgroundNames:["Rifrafters Campground","Arrowhead Bike Farm"],events:["Bridge overlook walk"]}
];
export const roadStops:RoadStop[]=[
 {id:"rs1",name:"Kentucky Horse Park Campground",type:"Public campground",minutesAhead:28,milesOffRoute:2.4,maxRigFt:45,pullThrough:true,electric:"30/50 amp",dogFriendly:true,price:40,availability:"Availability not live",direction:"north"},
 {id:"rs2",name:"Whispering Hills RV Park",type:"Private RV park",minutesAhead:52,milesOffRoute:1.8,maxRigFt:50,pullThrough:true,electric:"Full hookups",dogFriendly:true,price:52,availability:"Call to confirm",direction:"north"},
 {id:"rs3",name:"Big Bone Lick State Historic Site",type:"State park",minutesAhead:78,milesOffRoute:5.6,maxRigFt:40,pullThrough:false,electric:"Electric",dogFriendly:true,price:34,availability:"Availability not live",direction:"north"},
 {id:"rs4",name:"River Ridge Overnight",type:"Overnight parking",minutesAhead:108,milesOffRoute:.6,maxRigFt:55,pullThrough:true,electric:"None",dogFriendly:true,price:0,availability:"Permission required",direction:"north"}
];