import type { CampingPreference, DiscoverFilters, Interest, RigProfile, RoadStop, Trip } from "./types";
export const interests:Interest[]=["Scenic","Small towns","Hiking","Lake","Fishing","Events","Food","Museums","Amusement parks","Relaxing"];
export const campingPreferences:CampingPreference[]=["Full hookups","Electric","State park","Boondocking","Pull-through","Dog friendly"];
export const seededRig:RigProfile={home:"Pendleton, Kentucky 40055",rv:{year:2022,manufacturer:"Starcraft",model:"Autumn Ridge 26BHS",type:"Travel trailer",lengthFt:30.75,heightFt:11.08,widthFt:8,gvwr:7500,service:"30 amp",slides:1,freshTank:42,generator:false},towVehicle:{year:2025,manufacturer:"Chevrolet",model:"Silverado 2500HD",engine:"6.6L gasoline V8",fuel:"Gasoline",tankGallons:36,towingMpg:9}};
export const defaultFilters:DiscoverFilters={start:seededRig.home,leave:"2026-09-18",returnDate:"2026-09-20",maxDriveHours:4,adults:2,kids:2,dogs:1,interests:["Scenic","Hiking","Small towns"],preferences:["Electric","State park","Dog friendly"]};
export const trips:Trip[]=[
 {id:"red-river-gorge",destination:"Red River Gorge",region:"Slade, Kentucky",driveMinutes:142,distanceMiles:140,weather:"72° / 54° · Mock forecast",campgrounds:7,activities:18,tags:["Scenic","Hiking","Small towns"],preferences:["Electric","State park","Dog friendly"],fuelCost:93,campgroundCost:72,otherCost:20,image:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85",explanation:"Strong scenery, a manageable weekend drive, and enough nearby activities without spending half the weekend towing.",routeNote:"Mostly interstate with a short two-lane approach. No known seeded restriction conflicts.",novelty:82,weatherScore:92,priceScore:91,rigFit:98,activityScore:96,campgroundNames:["Middle Fork Campground","Whittleton Campground","Natural Bridge Campground"],events:["Mock: Mountain arts market","Mock: Guided natural bridge hike"]},
 {id:"brown-county",destination:"Brown County",region:"Nashville, Indiana",driveMinutes:128,distanceMiles:112,weather:"70° / 51° · Mock forecast",campgrounds:5,activities:14,tags:["Small towns","Food","Hiking"],preferences:["Electric","State park","Dog friendly"],fuelCost:75,campgroundCost:84,otherCost:35,image:"https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85",explanation:"A compact arts town, shaded trails, and an easy tow make this a low-friction weekend with plenty to explore.",routeNote:"Interstate-heavy route; campground approach should be verified with live routing.",novelty:76,weatherScore:89,priceScore:86,rigFit:94,activityScore:89,campgroundNames:["Brown County State Park","Bill Monroe Music Park"],events:["Mock: Village art walk","Mock: Local food festival"]},
 {id:"mammoth-cave",destination:"Mammoth Cave",region:"Cave City, Kentucky",driveMinutes:132,distanceMiles:121,weather:"74° / 56° · Mock forecast",campgrounds:8,activities:12,tags:["Hiking","Museums","Relaxing"],preferences:["Electric","State park","Pull-through"],fuelCost:81,campgroundCost:68,otherCost:38,image:"https://images.unsplash.com/photo-1443632864897-14973fa006cf?auto=format&fit=crop&w=1600&q=85",explanation:"A reliable rig-fit base with one standout anchor activity and a relaxed pace around the park.",routeNote:"Straightforward approach in seed data. Live height, weight, and closure checks are not yet connected.",novelty:70,weatherScore:91,priceScore:90,rigFit:97,activityScore:86,campgroundNames:["Mammoth Cave Campground","Cave Country RV Campground"],events:["Mock: Evening ranger program"]},
 {id:"hocking-hills",destination:"Hocking Hills",region:"Logan, Ohio",driveMinutes:205,distanceMiles:191,weather:"68° / 49° · Mock forecast",campgrounds:6,activities:16,tags:["Scenic","Hiking","Relaxing"],preferences:["Electric","State park","Dog friendly"],fuelCost:127,campgroundCost:92,otherCost:25,image:"https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=85",explanation:"The longest tow in this set earns its place with exceptional trail density and a quiet, scenic reset.",routeNote:"Within four hours in seed data. Final local-road suitability needs a live RV-aware route provider.",novelty:94,weatherScore:84,priceScore:78,rigFit:90,activityScore:94,campgroundNames:["Hocking Hills State Park","Top O’ the Caves"],events:["Mock: Naturalist night hike"]},
 {id:"land-between-lakes",destination:"Land Between the Lakes",region:"Golden Pond, Kentucky",driveMinutes:224,distanceMiles:220,weather:"76° / 58° · Mock forecast",campgrounds:9,activities:20,tags:["Lake","Fishing","Scenic"],preferences:["Electric","Boondocking","Dog friendly"],fuelCost:146,campgroundCost:64,otherCost:30,image:"https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1600&q=85",explanation:"Worth the longer pull for waterfront options, fishing, and room to spread out once you arrive.",routeNote:"Longer highway drive. Seeded options include sites reported to accommodate 31-foot trailers.",novelty:88,weatherScore:88,priceScore:84,rigFit:93,activityScore:95,campgroundNames:["Hillman Ferry Campground","Energy Lake Campground"],events:["Mock: Wildlife refuge program"]},
 {id:"new-river-gorge",destination:"New River Gorge",region:"Fayetteville, West Virginia",driveMinutes:245,distanceMiles:232,weather:"69° / 50° · Mock forecast",campgrounds:4,activities:17,tags:["Scenic","Hiking","Food"],preferences:["Electric","Dog friendly"],fuelCost:154,campgroundCost:96,otherCost:40,image:"https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1600&q=85",explanation:"A bigger weekend with dramatic scenery and a lively trail-town base, best when your drive window has some flexibility.",routeNote:"Slightly beyond the default four-hour limit and omitted unless tolerance is increased.",novelty:96,weatherScore:86,priceScore:71,rigFit:86,activityScore:96,campgroundNames:["Rifrafters Campground","Arrowhead Bike Farm"],events:["Mock: Bridge overlook walk"]}
];
export const roadStops:RoadStop[]=[
 {id:"rs1",name:"Kentucky Horse Park Campground",type:"Public campground",minutesAhead:28,milesOffRoute:2.4,maxRigFt:45,pullThrough:true,electric:"30/50 amp",dogFriendly:true,price:40,availability:"Availability not live",direction:"north"},
 {id:"rs2",name:"Whispering Hills RV Park",type:"Private RV park",minutesAhead:52,milesOffRoute:1.8,maxRigFt:50,pullThrough:true,electric:"Full hookups",dogFriendly:true,price:52,availability:"Call to confirm",direction:"north"},
 {id:"rs3",name:"Big Bone Lick State Historic Site",type:"State park",minutesAhead:78,milesOffRoute:5.6,maxRigFt:40,pullThrough:false,electric:"Electric",dogFriendly:true,price:34,availability:"Availability not live",direction:"north"},
 {id:"rs4",name:"River Ridge Overnight",type:"Overnight parking",minutesAhead:108,milesOffRoute:.6,maxRigFt:55,pullThrough:true,electric:"None",dogFriendly:true,price:0,availability:"Permission required",direction:"north"}
];
